### ISSUE TITLE
Sort on save

### ISSUE THREAD

**Issue by benjo696** [lysyi3m/atom-postcss-sorting#14]
Would it be possible to have a "sort-on-save" option like the Sublime package?

**Comment by paweljedrzejczyk** [comment]
I prepared PR for that #17

**Comment by lysyi3m** [comment]
@benjo696, now we have it! Will be in 2.7.0 release asap.

@paweljedrzejczyk, thank you for that 🍻

**Comment by benjo696** [comment]
Nice! Thanks :)
