### ISSUE TITLE
Disable cursor jump to the bottom on save?

### ISSUE THREAD

**Issue by hidace** [lysyi3m/atom-postcss-sorting#19]
Hi, 

Love this plugin, but wondering if there is a way to disable having the cursor jump to the bottom of the file on save?

Thanks!

**Comment by hidace** [comment]
Awesome! Thanks so much!!

**Comment by lysyi3m** [comment]
Thanks to @paweljedrzejczyk for that!  

@hidace check out latest 2.8.0 version

**Comment by hidace** [comment]
Yup, just got it - works great. Much appreciated!
