### ISSUE TITLE
Update postcss-sorting in deps

### ISSUE THREAD

**Issue by palegrow** [lysyi3m/atom-postcss-sorting#22]
Hello! Update postcss-sorting to [2.0.1](https://github.com/hudochenkov/postcss-sorting/releases) in deps, please. And [predefined configs](https://github.com/hudochenkov/postcss-sorting#migration-from-1x) too.

**Comment by lysyi3m** [comment]
@palegrow check out latest version https://github.com/lysyi3m/atom-postcss-sorting/releases/tag/v2.9.0
