### ISSUE TITLE
Feature request: find `.postcss-sorting.json` in any parent folder

### ISSUE THREAD

**Issue by palegrow** [lysyi3m/atom-postcss-sorting#24]
if I have project structure like this:
```sh
project/
  templates/
  static/
    package.json
    gulpfile.js
    .postcss-sorting.json
    component/
      component.css
```
Plugin can't find `.postcss-sorting.json`.

**Comment by lysyi3m** [comment]
`atom-postcss-sorting` is an Atom _editor_ plugin and it works in the context of [atom project](https://atom.io/docs/api/v1.13.1/Project), not in your project context. So it shouldn't process all of your folders recursively until `package.json` or `.postcss-sorting.json` will be founded. If you have any specific file structure, you should use "Custom path to config file" plugin option for that https://github.com/lysyi3m/atom-postcss-sorting#options
