### ISSUE TITLE
How to set .csscomb.json as a config file?

### ISSUE THREAD

**Issue by felixdorner** [lysyi3m/atom-postcss-sorting#33]
Great plugin but it does not seem to work with the .csscomb.json file? (http://csscomb.com/config)

According to your docs the config possibilities seem to be limited to either creating a .postcss-sorting.json file or to write the sorting settings in the package.json.

Another possibility I spot is to set a custom path to the config file. I tried something like this: `/.csscomb.json` but it didn't worked. (The path needs to be relative to the root of the current project.)

Is your plugin only working with the outlined configuration possibilities or does it also work with a .csscomb.json file. If yes, how would I approach this?

**Comment by lysyi3m** [comment]
Hey, @felixdorner! Thank you for feedback 🍻!

As mentioned in [README.md](https://github.com/lysyi3m/atom-postcss-sorting#acknowledgements) file this plugin based on [`postcss-sorting`](https://github.com/hudochenkov/postcss-sorting) package which was designed to provide an alternative way to sort, order & process CSS properties using PostCSS and have no official compatibility with CSScomb.

I have no plans to support CSScomb in `atom-postcss-sorting` plugin, especially if there is separate [`atom-csscomb`](https://github.com/bruce/atom-csscomb) package exists.
