### ISSUE TITLE
Error and success

### ISSUE THREAD

**Issue by dlewand691** [lysyi3m/atom-postcss-sorting#4]
When I run the plugin, I get an error of 
> Failed to read the config file "!

And then a success message right after, but nothing is sorted.

Thoughts? Running it on a .scss file.

**Comment by FNGR2911** [comment]
+1

**Comment by lysyi3m** [comment]
Hey, @dlewand691! Thanks for your feedback. Sorry about that. It should be fixed in v2.1.4. 
Let me know if the problem persists.
