### ISSUE TITLE
There's no way of passing options to postcss-sorting

### ISSUE THREAD

**Issue by fabiospampinato** [lysyi3m/atom-postcss-sorting#6]
I think there should be a way of passing options to `postcss-sorting`, otherwise there's basically no way we can customize it.

I suggest to use a file named `.postcss-sorting.json`, just looking for it recursively, maybe using [require-dot-file](https://www.npmjs.com/package/require-dot-file) should be enough. If we don't find it we simply fall back to the current logic.

**Comment by danielbayley** [comment]
+1. Except…
> If we don't find it we simply fall back to the current logic.

fallback to a default config file specified in the package settings (`atom.config.get 'postcss-sorting.globalConfig'` < `~/Path/to/globalConfig.json`) else fallback to one of the [predefined configs](https://github.com/hudochenkov/postcss-sorting/tree/master/configs), also set in package settings like…
```coffee
config:
  predefinedConfig:
    description: "Fallback to this predefined config…"
    type: 'string'
    default: 'default'
    enum: ['default', 'csscomb', 'yandex', 'zen']
```

Maybe there could also be a check in there for a `postcssSortingConfig` object in `package.json` somewhere?

**Comment by fabiospampinato** [comment]
I think there's no need to add another layer of opinions on top of the already provided configurations. 

I'm not sure what you are exactly requesting in the second part of your message but `default` is actually a preset on it's own, like `csscomb` or `yandex`. Unfortunately `default` was a poorly choice of name in my opinion.

Ps. Since for whatever reason my pull request as not already been merged if you need to have a custom configuration you can use my fork of this repo instead.

**Comment by danielbayley** [comment]
> I think there's no need to add another layer of opinions on top of the already provided configurations.

I agree, but I wasn't suggesting another _opinion_ (meaning another default config)… I meant that there should be another way of supplying your own (other than _having_ to pollute your project folder with yet another dotfile `.postcss-sorting.json`).

The second part of my suggestion was how this might be a file path you could supply via the package settings, along with the ability to choose _which_ default to fallback on if none is given (or no `.postcss-sorting.json` is found, as in your merged PR.)

But the last part of my suggestion is the main one I think; most _linters_ allow you to put your custom configs into an object in `package.json`, and I think this should follow that pattern.

I'll likely do a quick PR anyway…

**Comment by lysyi3m** [comment]
@danielbayley, thanks for your suggestion! 

 > I meant that there should be another way of supplying your own

it could be better to add support for some "global" config, stored in $HOME folder, for example.

> most linters allow you to put your custom configs into an object in package.json, and I think this should follow that pattern.

My short answer here is - no, I disagree. 
Let me explain. `package.json` file it's like a config file _for package/popject_ itself. It just provides some description, dependencies & other useful info for the correct working of package/application. But linters, hinters, sorters and so on - are not necessary for the application. They are just an optional tools for development. 
Another "minor" reason - I don't want to see additional ~200 LOC inside my `package.json` - it'll be ugly and unuseful. 
So, let it be config dotfile in project root directory with fallback to config in the $HOME directory or predefined preset. :)

**Comment by danielbayley** [comment]
> it could be better to add support for some "global" config, stored in $HOME folder, for example.

That should probably be supported, but again _optional_. I don't want another tool _forcing_ me to have yet _another_ dotfile polluting my `HOME` folder.

> I don't want to see additional ~200 LOC inside my package.json - it'll be ugly and unuseful.

You wouldn't have to… you could still do things _your_ way. But let me do things _mine_ :)

Personally I want to treat `package.json` as a _machine_ file and do all my config in `project.cson` (used by [project-manager]/[plus]. I've almost finished a _project-config_ package which automatically manages this stuff.

The main point here is that the user shouldn't be _forced_ to pollute directories with certain files because of _opinions_. Tools should be a bit more neutral/flexible.

Iv'e actually 99% done a PR anyway, which includes some other goodies, so you can take a look 👍 

[project-manager]: https://atom.io/packages/project-manager
[plus]: https://atom.io/packages/project-plus

**Comment by danielbayley** [comment]
> But linters, hinters, sorters and so on - are not necessary for the application. They are just an optional tools for development.

So are `devDependencies:` but they have to go in there :)

Anyway, see PR #13 for what I mean 👍

**Comment by lysyi3m** [comment]
nvm, @danielbayley, I've merged your PR. Thanks for that, really appreciate it! 👍

**Comment by lysyi3m** [comment]
So, since we have all necessary functionality to pass options in any kind, we could close this issue, I think.

**Comment by danielbayley** [comment]
Yeah cool. 👌 

Although I've since come across [_cosmiconfig_](https://github.com/davidtheclark/cosmiconfig) which seems like a more "standardised" way of handling config stuff… 💭
