### ISSUE TITLE
On Mac the shortcut is set to cmd+shift+s instead of ctrl+shift+s

### ISSUE THREAD

**Issue by fabiospampinato** [lysyi3m/atom-postcss-sorting#7]
In the `readme` it's stated the on Mac the shortcut used for triggering the plugin is `ctrl+shift+s`, while it's actually `cmd+shift+s` which by default is used for `File -> Save as...`

**Comment by lysyi3m** [comment]
Closed via https://github.com/lysyi3m/atom-postcss-sorting/pull/8
