### ISSUE TITLE
It should sort the buffer, not the actual content of the file

### ISSUE THREAD

**Issue by fabiospampinato** [lysyi3m/atom-postcss-sorting#9]
At the moment, when running `postcss-sort:run` it reads the actual content of the file we are working on and sorts it, when it should sort the opened buffer instead. 

An example case where this leads to a wrong behaviour is: open a file, edit it without saving and then sort it, no trace of your edits since they never got saved to the file.

**Comment by lysyi3m** [comment]
@fabiospampinato, v2.3.0 will sort the buffer content. Thanks for feedback.
